import './style.css';

const app = document.querySelector('#app');
const ASSETS=`${import.meta.env.BASE_URL}assets/`;
const KEY='misha-adventures-v1';
function loadState(){
  try{
    const saved=JSON.parse(localStorage.getItem(KEY)||'null');
    if(saved&&typeof saved.name==='string'&&Array.isArray(saved.done)) return {name:saved.name,done:[0,1,2].map(i=>Boolean(saved.done[i]))};
  }catch(e){ localStorage.removeItem(KEY) }
  return {name:'',done:[false,false,false]};
}
let state=loadState();
let screen='start', step=0, mistakes=0, feedback='', bagSequence=[], objectSequence=[], showingLastMove=false, agentOpen=false;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const icons={bag:'🎒',rocket:'🚀',vault:'🔐'};
const shuffle=a=>{const copy=[...a];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};

const SOUND_KEY='misha-adventures-sound';
let soundOn=localStorage.getItem(SOUND_KEY)!=='off',audioCtx=null,musicTimer=null,audioStarted=false;
function ensureAudio(){if(!soundOn)return null;audioCtx??=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function tone(freq,delay=.0,duration=.16,volume=.035,type='sine'){
  const ctx=ensureAudio();if(!ctx)return;const osc=ctx.createOscillator(),gain=ctx.createGain(),start=ctx.currentTime+delay;
  osc.type=type;osc.frequency.setValueAtTime(freq,start);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(volume,start+.025);gain.gain.exponentialRampToValueAtTime(.0001,start+duration);
  osc.connect(gain).connect(ctx.destination);osc.start(start);osc.stop(start+duration+.03)
}
function noiseBeat(delay=0,volume=.004){const ctx=ensureAudio();if(!ctx)return;const length=Math.floor(ctx.sampleRate*.045),buffer=ctx.createBuffer(1,length,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*(1-i/length);const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain(),start=ctx.currentTime+delay;filter.type='highpass';filter.frequency.value=2600;gain.gain.setValueAtTime(volume,start);gain.gain.exponentialRampToValueAtTime(.0001,start+.05);source.buffer=buffer;source.connect(filter).connect(gain).connect(ctx.destination);source.start(start)}
function playSound(name){if(!soundOn)return;const sounds={
  click:()=>tone(420,0,.08,.018,'triangle'),
  correct:()=>{tone(523,0,.15,.04,'triangle');tone(659,.1,.18,.04,'triangle');tone(784,.2,.24,.035,'triangle')},
  wrong:()=>{tone(210,0,.16,.035,'sawtooth');tone(165,.12,.22,.025,'sawtooth')},
  pack:()=>{tone(330,0,.12,.03,'triangle');tone(495,.1,.16,.035,'triangle');tone(660,.2,.22,.03,'sine')},
  rocket:()=>{tone(180,0,.3,.025,'sawtooth');tone(260,.12,.3,.022,'sawtooth');tone(520,.28,.2,.03,'triangle')},
  code:()=>{tone(620,0,.09,.03,'square');tone(820,.1,.12,.025,'square')},
  vault:()=>{tone(110,0,.45,.045,'triangle');tone(220,.18,.42,.035,'triangle');tone(440,.42,.4,.03,'sine');tone(660,.62,.45,.035,'triangle')},
  win:()=>[392,523,659,784,1047].forEach((n,i)=>tone(n,i*.13,.42,.035,'triangle'))
  };(sounds[name]||sounds.click)()
}
function musicPulse(){if(!soundOn||!audioStarted)return;const melody=[392,523.25,659.25,783.99,659.25,523.25,440,587.33,698.46,880,698.46,587.33,523.25,659.25,783.99,1046.5];melody.forEach((n,i)=>{tone(n,i*.28,.24,.016,'triangle');noiseBeat(i*.28,.0035)});[130.81,196,174.61,220,146.83,220,196,261.63].forEach((n,i)=>{tone(n,i*.56,.4,.013,'sine');tone(82.41,i*.56,.1,.016,'sine')})}
function startMusic(){if(!soundOn||musicTimer)return;audioStarted=true;ensureAudio();musicPulse();musicTimer=setInterval(musicPulse,4700)}
function stopMusic(){clearInterval(musicTimer);musicTimer=null}
function toggleSound(){soundOn=!soundOn;localStorage.setItem(SOUND_KEY,soundOn?'on':'off');if(soundOn){startMusic();playSound('correct')}else stopMusic();document.querySelectorAll('[data-sound]').forEach(b=>{b.textContent=soundOn?'🔊':'🔇';b.setAttribute('aria-label',soundOn?'Mute sounds':'Turn sounds on')})}
document.addEventListener('pointerdown',()=>startMusic(),{once:true});
document.addEventListener('click',e=>{if(e.target.closest('button')&&!e.target.closest('[data-sound]'))playSound('click')});

const HOW_TO_PLAY=[
  {title:'Pack the Bag',steps:['Read Misha’s instruction.','Choose the matching object.','Pack all 5 things into the backpack.']},
  {title:'Space Mission',steps:['Read the English sentence.','Choose the correct answer.','Each correct answer moves the rocket closer to the station.']},
  {title:'Secret Agent',steps:['Choose the correct word or sentence.','Each answer reveals one code digit.','Find all 4 digits to open the secret vault.']}
];
function openHowTo(index){const info=HOW_TO_PLAY[index],modal=document.createElement('div');modal.className='how-modal';modal.innerHTML=`<div class="how-dialog" role="dialog" aria-modal="true" aria-labelledby="howTitle"><button class="how-close" aria-label="Close">×</button><span class="eyebrow">HOW TO PLAY</span><h2 id="howTitle">${info.title}</h2><ol>${info.steps.map(step=>`<li>${step}</li>`).join('')}</ol><button class="primary how-got-it">Got it! ▶</button></div>`;document.querySelector('.app').append(modal);const close=()=>modal.remove();modal.querySelector('.how-close').onclick=close;modal.querySelector('.how-got-it').onclick=close;modal.onclick=e=>{if(e.target===modal)close()}}
document.addEventListener('click',e=>{const cardHelp=e.target.closest('[data-help-card]'),gameHelp=e.target.closest('[data-how-to]');if(cardHelp)openHowTo(+cardHelp.dataset.helpCard);if(gameHelp)openHowTo(['bag','space','agent'].indexOf(screen))});

function shell(content,cls=''){
  const gameHelp=['bag','space','agent'].includes(screen)?'<button class="how-to-game" data-how-to>❔ How to play</button>':'';
  app.innerHTML=`<main class="app ${cls}"><div class="stars"></div><button class="sound" data-sound aria-label="${soundOn?'Mute sounds':'Turn sounds on'}">${soundOn?'🔊':'🔇'}</button>${gameHelp}${content}<footer>✦ &nbsp; Learn English. <b>Have fun.</b> Go on adventures! &nbsp; ★</footer></main>`;
  document.querySelector('[data-sound]').onclick=toggleSound;
  const howButton=document.querySelector('[data-how-to]');if(howButton)howButton.onclick=e=>{e.stopPropagation();openHowTo(['bag','space','agent'].indexOf(screen))};
}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function logo(){return `<div class="logo"><strong>Misha’s Adventures</strong></div>`}
function renderStart(){shell(`<section class="start-wrap"><div class="start-card">${logo()}<div class="misha-badge"><img src="${ASSETS}misha-room-v6.png" alt="Misha"></div><h1>Hi! I’m Misha.</h1><p>Ready for an adventure?</p><label for="name">What’s your name?</label><input id="name" type="text" maxlength="24" placeholder="Enter your name" autocomplete="name" spellcheck="false"><button class="primary" id="startBtn" type="button" disabled>Start Adventure <span>▶</span></button><small>3 missions · 1 big adventure</small></div></section>`,'start-screen');const inp=document.querySelector('#name'),btn=document.querySelector('#startBtn');const sync=()=>{btn.disabled=inp.value.trim().length===0};['input','change','keyup'].forEach(event=>inp.addEventListener(event,sync));inp.addEventListener('paste',()=>setTimeout(sync,0));inp.addEventListener('keydown',e=>{if(e.key==='Enter'&&inp.value.trim()){e.preventDefault();btn.click()}});btn.addEventListener('click',()=>{const name=inp.value.trim();if(!name){inp.focus();return}state={name,done:[false,false,false]};save();screen='home';render()});setTimeout(()=>inp.focus(),0)}
function renderHome(){let completed=state.done.filter(Boolean).length;shell(`<header class="top">${logo()}</header><section class="home-copy"><span class="eyebrow">YOUR MISSION</span><h1>Ready, ${esc(state.name)}?</h1><p>Complete all 3 games and unlock the treasure!</p></section><section class="missions">${card(0,'Pack the Bag','Help Misha get ready!',ASSETS+'mission-bag.png','teal',true)}${card(1,'Space Mission','Fly to the Secret Station!',ASSETS+'mission-rocket.png','blue',state.done[0])}${card(2,'Secret Agent','Crack the code and open the vault!',ASSETS+'mission-vault.png','purple',state.done[1])}</section><div class="journey"><span>📋 <b>Complete all 3 games</b></span><i>•</i><span>🧰 <b>Unlock the treasure</b></span><i>•</i><span>🏆 <b>Get your Award</b></span></div>`,'home-screen');document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>{step=0;mistakes=0;feedback='';agentOpen=false;screen=['bag','space','agent'][+b.dataset.play];if(screen==='bag'){bagSequence=shuffle(bagTasks);objectSequence=shuffle(objects)}render()})}
function card(i,title,sub,image,color,unlocked){let done=state.done[i];return `<article class="mission ${color} ${unlocked?'':'locked'}"><span class="num">${i+1}</span><button class="card-help" data-help-card="${i}">? <span>How to play</span></button><div class="card-art"><img src="${image}" alt=""></div><h2>${title}</h2><p>${sub}</p><button data-play="${i}" ${unlocked?'':'disabled'}>${done?'✓ COMPLETED':unlocked?'PLAY ▶':'LOCKED 🔒'}</button></article>`}

const bagTasks=[['Put the map in the bag.','map'],['Take something to drink.','water'],['Pack something to eat.','sandwich'],['Take the red cap.','cap'],["It’s dark. Take the flashlight.",'flashlight']];
const objects=[['map','map'],['water','water'],['sandwich','sandwich'],['cap','red-cap'],['flashlight','flashlight'],['helicopter','helicopter'],['teddy','teddy'],['book','book'],['ball','ball']];
function itemImg(id){const item=objects.find(o=>o[0]===id);return `<img src="${ASSETS}item-${item?.[1]||id}.png" alt="">`}
function renderBag(){if(!bagSequence.length){bagSequence=shuffle(bagTasks);objectSequence=shuffle(objects)}if(step>=5&&!showingLastMove)return finishGame(0,"Great! My bag is ready. Let’s go!",'🎒');const task=bagSequence[Math.min(step,4)],collected=bagSequence.slice(0,step),complete=step>=5;shell(`<header class="game-head"><button data-home>← Missions</button><div><span>MISSION 1</span><h1>Pack the Bag</h1></div><div class="task-count">${Math.min(step+1,5)} / 5</div></header><section class="game-layout warm"><div class="scene"><div class="speech">${complete?'Great! My bag is ready!':task[0]}</div><div class="object-grid">${objectSequence.map(([id,file])=>`<button class="object ${collected.some(t=>t[1]===id)?'packed':''}" data-answer="${id}" aria-label="${id}" ${complete?'disabled':''}><img src="${ASSETS}item-${file}.png" alt=""></button>`).join('')}</div>${complete?'<div class="feedback show">All packed! ✨</div>':feedbackBox()}</div><aside class="pack-visual"><img class="pack-scene-img" src="${ASSETS}pack-scene-v4.png" alt="Misha with an open backpack"><div class="filled-items">${[0,1,2,3,4].map((_,i)=>`<span class="slot slot-${i} ${i<collected.length?'filled':''}">${i<collected.length?itemImg(collected[i][1]):''}</span>`).join('')}</div><div class="bag-counter"><b>${step}</b> of 5 packed</div></aside></section>`,'game bag-game');if(!complete)bindAnswers(task[1])}

const spaceTasks=[['Misha ___ ready.',['am','is','are'],'is'],['He ___ a blue suit.',['have got','has got','is got'],'has got'],['A rocket can ___.',['swim','fly','read'],'fly'],['We ___ in space now.',['am','is','are'],'are'],['🪐  What is this?',['helmet','map','planet'],'planet'],['Misha ___ space adventures.',['like','likes','liking'],'likes']];
function renderSpace(){if(step>=6&&!showingLastMove)return finishGame(1,'We made it! But the treasure is locked...','🚀');const complete=step>=6,t=spaceTasks[Math.min(step,5)];shell(`<header class="game-head"><button data-home>← Missions</button><div><span>MISSION 2</span><h1>Space Mission</h1></div><div class="task-count">${Math.min(step+1,6)} / 6</div></header><section class="space-scene"><div class="route">${['🌎','🪐','🔵','🌙','🟣','🛰️','🏢'].map((x,i)=>`<div class="waypoint ${i<=step?'reached':''}">${i===step?`<img class="route-rocket" src="${ASSETS}space-rocket-misha.png" alt="Misha flying in his rocket">`:``}<span>${x}</span><small>${i===0?'START':i===6?'STATION':''}</small></div>`).join('<i>···</i>')}</div><div class="quiz-card ${complete?'arrival':''}"><span class="eyebrow">${complete?'SECRET STATION REACHED':'CHOOSE THE ANSWER'}</span><h2>${complete?'We made it! 🚀':t[0]}</h2>${complete?'<div class="feedback show">Landing complete! ✨</div>':`<div class="answers">${t[1].map(a=>`<button data-answer="${a}">${a}</button>`).join('')}</div>${feedbackBox()}`}</div></section>`,'game space-game');if(!complete)bindAnswers(t[2])}

const agentTasks=[["Choose the correct sentence.",['Misha have got a map.','Misha has got a map.','Misha is got a map.'],'Misha has got a map.'],['🔦  What is it?',['sandwich','cap','flashlight'],'flashlight'],['I can ___ English.',['speak','speaks','speaking'],'speak'],['Choose the correct sentence.',['Misha like adventures.','Misha likes adventures.','Misha liking adventures.'],'Misha likes adventures.']];
function renderAgent(){if(step>=4&&!showingLastMove)return finishGame(2,'ACCESS GRANTED — We did it!','🏆');const complete=step>=4,open=complete&&agentOpen,t=agentTasks[Math.min(step,3)],digits='3725';shell(`<header class="game-head"><button data-home>← Missions</button><div><span>MISSION 3</span><h1>Secret Agent</h1></div><div class="task-count">${Math.min(step+1,4)} / 4</div></header><section class="agent-scene"><div class="agent-visual ${open?'open':''}"><img src="${ASSETS}${open?'agent-open':'agent-locked'}.png" alt="${open?'Happy Misha beside the open vault':'Puzzled Misha beside the locked vault'}"><div class="code">${[0,1,2,3].map(i=>`<b>${i<step?digits[i]:'_'}</b>`).join('')}</div></div><div class="quiz-card purple-card ${complete?'access-card':''}"><span class="eyebrow">${complete?(open?'ACCESS GRANTED':'CODE COMPLETE'):'CRACK THE CODE'}</span><h2>${complete?(open?'The vault is open!':'3 7 2 5'):t[0]}</h2>${complete?`<div class="feedback show">${open?'We did it! ✨':'Unlocking…'}</div>`:`<div class="answers">${t[1].map(a=>`<button data-answer="${a}">${a}</button>`).join('')}</div>${feedbackBox()}`}</div></section>`,'game agent-game');if(!complete)bindAnswers(t[2])}
function feedbackBox(){return `<div class="feedback ${feedback?'show':''}">${feedback||'&nbsp;'}</div>`}
function bindAnswers(correct){document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(b.dataset.answer===correct){b.classList.add('correct');feedback='Great! ✨';playSound(screen==='bag'?'pack':screen==='space'?'rocket':'code');const finalMove=(screen==='bag'&&step===4)||(screen==='space'&&step===5)||(screen==='agent'&&step===3);setTimeout(()=>{step++;mistakes=0;feedback='';if(finalMove){const completedScreen=screen;showingLastMove=true;render();if(completedScreen==='agent')setTimeout(()=>{if(screen===completedScreen){agentOpen=true;playSound('vault');render()}},800);setTimeout(()=>{if(screen!==completedScreen)return;showingLastMove=false;if(screen==='bag')finishGame(0,"Great! My bag is ready. Let’s go!",'🎒');else if(screen==='space')finishGame(1,'We made it! But the treasure is locked...','🚀');else finishGame(2,'ACCESS GRANTED — We did it!','🏆')},completedScreen==='agent'?2500:1900)}else render()},550)}else{b.classList.add('wrong');playSound('wrong');mistakes++;feedback=mistakes>1?'Almost! Look for the glowing answer.':'Oops! Try again.';document.querySelectorAll('[data-answer]').forEach(x=>x.classList.toggle('hint',mistakes>1&&x.dataset.answer===correct));document.querySelector('.feedback').outerHTML=feedbackBox()}})}
function finishGame(i,text,emoji){playSound('win');state.done[i]=true;save();if(i===2){screen='final';return render()}const art=i===0?`<img class="finish-misha" src="${ASSETS}pack-finale-v4.png" alt="Happy Misha with his packed backpack">`:`<img class="finish-misha" src="${ASSETS}space-finale.png" alt="Misha with his closed backpack beside the rocket">`;shell(`<section class="finish ${i===0?'pack-finish':'space-finish'}">${art}<div class="finish-copy"><span class="eyebrow">MISSION COMPLETE</span><h1>${text}</h1><p>${i===0?'Space Mission is now unlocked!':'Secret Agent is now unlocked. We need the secret code!'}</p><button class="primary" id="continue">Continue ▶</button></div></section>`,'game finish-screen');document.querySelector('#continue').onclick=()=>{screen='home';render()}}

function renderFinal(){shell(`<section class="final"><div class="confetti">✦ ★ ✧ ★ ✦</div><span class="eyebrow">ALL 3 MISSIONS COMPLETE</span><h1>Mission Complete!</h1><p>Well done, <b>${esc(state.name)}</b>!</p><p>You helped Misha complete his mission!</p><div class="trophies"><span>🎒</span><span>🚀</span><span>🔓</span></div><div class="certificate" id="certificate"><small>CERTIFICATE OF ACHIEVEMENT</small><h2>Certificate of Achievement</h2><p>This certificate is proudly awarded to</p><strong>${esc(state.name)}</strong><i></i><p>for helping Misha complete his mission<br>and for being ready to reach new heights<br>in new English adventures!</p><b>Mission Complete!</b><div>★ &nbsp; MISHA’S ADVENTURES &nbsp; ★</div></div><div class="final-actions"><button class="primary" id="download">Download Certificate ↓</button><button id="again">Play Again</button><button data-home>Back to Home</button></div></section>`,'game final-screen');document.querySelector('#download').onclick=downloadCertificate;document.querySelector('#again').onclick=()=>{state.done=[false,false,false];save();screen='home';render()}}

function downloadCertificate(){const c=document.createElement('canvas');c.width=1600;c.height=1131;const x=c.getContext('2d');let g=x.createLinearGradient(0,0,1600,1131);g.addColorStop(0,'#f8fbff');g.addColorStop(1,'#dff9ff');x.fillStyle=g;x.fillRect(0,0,c.width,c.height);x.strokeStyle='#0aaebd';x.lineWidth=18;x.strokeRect(35,35,1530,1061);x.strokeStyle='#f2b534';x.lineWidth=5;x.strokeRect(57,57,1486,1017);x.textAlign='center';x.fillStyle='#09234a';x.font='bold 34px Nunito';x.fillText("MISHA’S ADVENTURES",800,145);x.fillStyle='#079aa8';x.font='bold 76px Georgia';x.fillText('Certificate of Achievement',800,275);x.fillStyle='#3a506d';x.font='30px Nunito';x.fillText('This certificate is proudly awarded to',800,380);x.fillStyle='#09234a';x.font='bold 82px Georgia';x.fillText(state.name,800,505);x.strokeStyle='#f2b534';x.lineWidth=3;x.beginPath();x.moveTo(400,535);x.lineTo(1200,535);x.stroke();x.fillStyle='#3a506d';x.font='29px Nunito';['for helping Misha complete his mission','and for being ready to reach new heights','in new English adventures!'].forEach((s,i)=>x.fillText(s,800,635+i*45));x.fillStyle='#7b3fc6';x.font='bold 48px Nunito';x.fillText('Mission Complete!',800,820);x.font='62px serif';x.fillText('★   🎒   🚀   🔐   ★',800,930);x.fillStyle='#079aa8';x.font='bold 25px Nunito';x.fillText('KEEP LEARNING • KEEP EXPLORING',800,1030);canvasToPdf(c,`Mishas_Adventures_${state.name.replace(/[^a-zа-яё0-9]/gi,'_')}_Certificate.pdf`)}
function canvasToPdf(canvas,name){const jpg=atob(canvas.toDataURL('image/jpeg',.94).split(',')[1]);const enc=new TextEncoder(),parts=[],offsets=[0];let size=0;const add=s=>{let a=typeof s==='string'?enc.encode(s):s;parts.push(a);size+=a.length};add('%PDF-1.4\n');function obj(n,s){offsets[n]=size;add(`${n} 0 obj\n${s}\nendobj\n`)}obj(1,'<< /Type /Catalog /Pages 2 0 R >>');obj(2,'<< /Type /Pages /Kids [3 0 R] /Count 1 >>');obj(3,'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /XObject << /Im0 5 0 R >> >> /Contents 4 0 R >>');let stream='q 842 0 0 595 0 0 cm /Im0 Do Q';obj(4,`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);offsets[5]=size;add(`5 0 obj\n<< /Type /XObject /Subtype /Image /Width ${canvas.width} /Height ${canvas.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpg.length} >>\nstream\n`);add(Uint8Array.from(jpg,c=>c.charCodeAt(0)));add('\nendstream\nendobj\n');let start=size;add('xref\n0 6\n0000000000 65535 f \n');for(let i=1;i<=5;i++)add(String(offsets[i]).padStart(10,'0')+' 00000 n \n');add(`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`);let blob=new Blob(parts,{type:'application/pdf'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function render(){({start:renderStart,home:renderHome,bag:renderBag,space:renderSpace,agent:renderAgent,final:awardRenderFinal}[screen])();document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>{screen='home';render()})}
render();

/* Restyled all-missions award screen. Function declarations are intentionally
   kept last so this presentation replaces the legacy certificate renderer. */
function awardRenderFinal(){shell(`<section class="final"><div class="confetti">✦ ★ ✧ ★ ✦</div><h1>All Three Missions Complete!</h1><p class="well-done">Well done, <b>${esc(state.name)}</b>!</p><div class="certificate" id="certificate"><div class="certificate-copy"><small>CERTIFICATE OF ACHIEVEMENT</small><h2>Certificate of Achievement</h2><p>This certificate is proudly awarded to</p><strong>${esc(state.name)}</strong><i></i><p>for helping Misha complete his mission<br>and for being ready to reach new heights<br>in new English adventures!</p><b>Mission Complete!</b><div>MISHA’S ADVENTURES</div></div></div><div class="final-actions"><button class="primary" id="download">Download Certificate ↓</button><button id="again">Play Again</button><button data-home>Back to Home</button></div></section>`,'game final-screen');document.querySelector('#download').onclick=awardDownloadCertificate;document.querySelector('#again').onclick=()=>{state.done=[false,false,false];save();screen='home';render()}}

async function awardDownloadCertificate(){const c=document.createElement('canvas');c.width=1600;c.height=1131;const x=c.getContext('2d');const bg=await new Promise((resolve,reject)=>{const img=new Image;img.onload=()=>resolve(img);img.onerror=reject;img.src=ASSETS+'certificate-bg-v2.png'});x.drawImage(bg,0,0,c.width,c.height);const cx=650;x.textAlign='center';x.fillStyle='#087d91';x.font='bold 62px Georgia';x.fillText('Certificate of Achievement',cx,275);x.fillStyle='#42556c';x.font='28px Nunito';x.fillText('This certificate is proudly awarded to',cx,355);x.fillStyle='#102c4c';x.font='bold 76px Georgia';x.fillText(state.name,cx,455);x.strokeStyle='#d5a52e';x.lineWidth=3;x.beginPath();x.moveTo(295,482);x.lineTo(1005,482);x.stroke();x.fillStyle='#42556c';x.font='27px Nunito';['for helping Misha complete his mission','and for being ready to reach new heights','in new English adventures!'].forEach((s,i)=>x.fillText(s,cx,565+i*42));x.fillStyle='#693a9b';x.font='bold 43px Nunito';x.fillText('Mission Complete!',cx,755);x.fillStyle='#087d91';x.font='bold 23px Nunito';x.fillText('KEEP LEARNING • KEEP EXPLORING',cx,825);canvasToPdf(c,`Mishas_Adventures_${state.name.replace(/[^a-zа-яё0-9]/gi,'_')}_Certificate.pdf`)}
